apiVersion: v1
kind: Service
metadata:
  name: demomockserver-c5dl51mdps80
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: redis
    role: master
    tier: backend

